// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });

// Placeholder to prevent import errors during migration
export const supabase = {
  from: () => ({
    select: () => ({ eq: () => ({ single: () => ({}), order: () => ({}) }) }),
    upload: () => ({}),
    getPublicUrl: () => ({ data: { publicUrl: "" } }),
  }),
  auth: {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { } } } }),
    getSession: async () => ({ data: { session: null } }),
    signInWithPassword: async () => ({ error: { message: "Supabase disabled" } }),
    signUp: async () => ({ error: { message: "Supabase disabled" } }),
    signOut: async () => { },
  },
  storage: {
    from: () => ({
      upload: async () => ({ error: null }),
      getPublicUrl: () => ({ data: { publicUrl: "" } })
    })
  },
  channel: () => ({
    on: () => ({ subscribe: () => { } })
  }),
  removeChannel: () => { }
};